upd

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -27,8 +27,14 @@ jobs:
       - name: Build Project
         run: npm run build
 
-      - name: List build files
-        run: ls -R .next
+      - name: Debug Working Directory
+        run: ls -alh
+
+      - name: Debug .next Directory
+        run: ls -R .next || echo ".next directory not found"
+
+      - name: Debug Out Directory
+        run: ls -R out || echo "out directory not found"
 
       - name: Upload production-ready build files
         uses: actions/upload-artifact@v3
